controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#    # API Route
#api_register:
#    path: '/api/register'
#    controller: App\Controller\RegistrationController::register
#    methods: ['POST']
#
#app:
#    path: '/{reactRouting}'
#    controller: App\Controller\DefaultController::index
#    requirements:
#        reactRouting: '^(?!api).+'
#    defaults:
#        reactRouting: null